version: 3.9
services:
  mongo_db_test:
    container_name: mongo_db_server_test
    image: mongo:latest
    ports:
      - 27025:27017
    volumes:
      - ./d/DOCKER/MONGO:/data/db
  api: 
    container_name: api_server_test
    build: .
    ports:
      - 5000:8080   # puerto local:puerto del contenedor
    environment:
      MONGO_URL: mongo_db://mongo_db_test:27017

# docker-compose up